"""The published xP board (ADR-213).

The pipeline now publishes *analytics*, not just data — because a Flutter client cannot call `decision_xp`,
and the mobile audit's §4.1 read surface assumes the answer is in the database.

⭐⭐ **The hazard this whole file exists for: the same number now lives in two places.** That is what ADRs
123, 127 and 181 are each about, and it is tolerable here only because the stored copy is *generated by the
canonical one* every tick — pinned below by recomputing and comparing, so a divergence **fails** rather than
drifting quietly onto a phone.
"""

import json
from datetime import UTC, datetime

import pytest

from src import pipeline
from src.analytics.xp import decision_xp
from src.storage import Storage

STAMP = datetime(2026, 9, 20, 18, 0, tzinfo=UTC).isoformat(timespec="seconds")


@pytest.fixture
def store(tmp_path, monkeypatch):
    """A store holding the real board — on **whichever backend the suite is pointed at**.

    ⚠️ **Two constraints that pull in opposite directions, and the first attempt satisfied only one.**

    1. It must not open the committed `data/seed.db`, because `Storage()` migrates what it opens and that
       file is in git. So: a copy. (`shutil.copy` carries the source's permission bits — the chmod is not
       decoration.)
    2. Under `MADBOOTS_TEST_DSN` the harness ignores the path and hands back Postgres, copying the snapshot
       in **only when the caller asked for `config.DB_PATH` or `config.SEED_DB_PATH`**. A bare `tmp_path`
       reads as *"this test builds its own fixture"* — so the store came back **empty** and all twelve tests
       failed on Postgres while passing on SQLite.

    ⭐ Pointing `config.SEED_DB_PATH` *at the copy* satisfies both: SQLite opens the copy, and Postgres
    recognises the request and seeds itself. ⚠️ Marking these `sqlite_only` would have been the easy way out
    and the wrong one — **the pipeline runs on Postgres**, so these are the tests that matter most there.
    """
    import shutil

    from src import config
    target = tmp_path / "board.db"
    shutil.copy(config.SEED_DB_PATH, target)
    target.chmod(0o644)
    monkeypatch.setattr(config, "SEED_DB_PATH", str(target))
    s = Storage(config.SEED_DB_PATH)
    yield s
    s.close()


def _fresh(store, horizon=pipeline.XP_BOARD_HORIZON):
    return decision_xp(store.get_players(), store.get_upcoming_fixtures(),
                       store.get_history_by_code(), horizon=horizon,
                       gw_history_by_code=store.get_gw_history_by_code())


# ---- one recipe ------------------------------------------------------------------------

def test_the_published_board_matches_a_fresh_computation(store):
    """⭐⭐ **The guard that makes the second copy safe.** Ask "if the pipeline grew its own xP maths, would
    this fail?" — it would, which is the whole point."""
    pipeline.publish_board(store, computed_at=STAMP)
    stored = {r["id"]: r for r in store.get_xp_board()}
    live = _fresh(store)

    assert len(stored) == len(live), "every player the engine prices must reach the board"
    for row in live:
        pub = stored[row["id"]]
        assert pub["web_name"] == row["web_name"]
        assert pub["by_gameweek"] == pytest.approx(row["by_gameweek_exact"]), (
            f"{row['web_name']}: the published board disagrees with decision_xp")


def test_every_horizon_the_ui_offers_is_derivable_from_the_one_board(store):
    """⭐ The reason it is one row per player rather than eight.

    The UI's slider runs 1–8. If a client could not reconstruct each total exactly, the table would have to
    hold all eight — or, worse, the client would sum the rounded display values and drift.
    """
    pipeline.publish_board(store, computed_at=STAMP)
    stored = {r["id"]: r for r in store.get_xp_board()}

    for horizon in range(1, pipeline.XP_BOARD_HORIZON + 1):
        for row in _fresh(store, horizon=horizon):
            gws = sorted(stored[row["id"]]["by_gameweek"])[:horizon]
            derived = round(sum(stored[row["id"]]["by_gameweek"][g] for g in gws), 1)
            assert derived == pytest.approx(row["xp"], abs=1e-9), (
                f"horizon {horizon}, {row['web_name']}: derived {derived} vs engine {row['xp']}")


def test_the_stored_values_are_unrounded(store):
    """⚠️ Publishing the *rounded* breakdown is the subtle version of this bug: it looks right, and the drift
    only appears when a client sums a prefix. So the table must hold more precision than the display."""
    pipeline.publish_board(store, computed_at=STAMP)
    raw = store.conn.execute("SELECT by_gameweek FROM xp_board").fetchall()
    values = [v for row in raw for v in json.loads(row["by_gameweek"]).values()]
    assert any(round(v, 1) != v for v in values), "every stored value is at 1dp — precision was lost"


# ---- refuse rather than corrupt --------------------------------------------------------

def test_an_empty_board_is_refused(store):
    with pytest.raises(pipeline.BoardRejected, match="empty"):
        pipeline.validate_board([], store.get_players())


def test_a_board_of_zeros_is_refused(store):
    """⭐ *The failure that produces a plausible-looking answer is the one worth a check.* A broken history
    load does not raise — it scores nobody, and every screen renders happily."""
    board = [dict(r, by_gameweek_exact={6: 0.0}) for r in _fresh(store)]
    with pytest.raises(pipeline.BoardRejected, match="zero"):
        pipeline.validate_board(board, store.get_players())


def test_a_half_sized_board_is_refused(store):
    players = store.get_players()
    with pytest.raises(pipeline.BoardRejected, match="rows for"):
        pipeline.validate_board(_fresh(store)[:10], players)


def test_an_implausible_score_is_refused(store):
    board = _fresh(store)
    board[0]["by_gameweek_exact"] = {6: 500.0}
    with pytest.raises(pipeline.BoardRejected, match="implausible"):
        pipeline.validate_board(board, store.get_players())


def test_a_refused_board_leaves_the_last_good_one_serving(store, monkeypatch):
    """⚠️ **The property that makes validation worth having.** Rejecting is only useful if the previous board
    survives — otherwise a bad tick still takes the feature down, just more politely."""
    pipeline.publish_board(store, computed_at=STAMP)
    good = store.get_xp_board()
    assert good

    monkeypatch.setattr(pipeline, "validate_board",
                        lambda *a, **k: (_ for _ in ()).throw(pipeline.BoardRejected("nope")))
    with pytest.raises(pipeline.BoardRejected):
        pipeline.publish_board(store, computed_at="2026-09-21T00:00:00+00:00")

    after = store.get_xp_board()
    assert after == good, "the refused run must not have touched the published board"


# ---- the anchor ------------------------------------------------------------------------

def test_the_board_records_which_gameweeks_it_covers(store):
    """⚠️ `by_gameweek` is keyed by real gameweek numbers, so the window moves at every deadline. Without the
    anchor a stale board is indistinguishable from a current one."""
    out = pipeline.publish_board(store, computed_at=STAMP)
    rows = store.get_xp_board()
    assert out["first_event"] == min(min(r["by_gameweek"]) for r in rows)
    assert {r["first_event"] for r in rows} == {out["first_event"]}, "one board, one window"
    assert {r["computed_at"] for r in rows} == {STAMP}


def test_publishing_replaces_rather_than_merges(store):
    """⭐ A board is a snapshot of one moment. Merging would leave rows from two windows side by side — which
    is harder to notice than a wholly stale board, and `first_event` would no longer mean anything."""
    pipeline.publish_board(store, computed_at=STAMP)
    before = len(store.get_xp_board())
    store.conn.execute("DELETE FROM xp_board WHERE element_id > 100")
    store.conn.commit()
    pipeline.publish_board(store, computed_at="2026-09-21T00:00:00+00:00")
    assert len(store.get_xp_board()) == before


def test_no_board_published_reads_as_empty_not_as_zeros(store):
    """Deliberately distinct: *"the pipeline has not run"* must not look like *"nobody scores"*."""
    assert store.get_xp_board() == []


# ---- how a rejected board is reported (the pipeline tick) -------------------------------

def test_a_rejected_board_still_reports_the_DATA_as_refreshed(store, monkeypatch):
    """⭐⭐ **The subtle half, and the first version got it wrong.**

    By the time the board is computed, `ingest.refresh` has already written the players — the raw data
    genuinely refreshed. The sidebar reads `refreshed_at` and nothing else. Withholding it because the
    *board* failed would make the app report **stale data that is actually fresh**, which is a false alarm
    nobody could diagnose from the screen.

    ⭐ *Each artefact reports its own freshness.* The board's age is `xp_board.computed_at`, which is
    untouched precisely because the refused board never replaced it.
    """
    pipeline.publish_board(store, computed_at="2026-09-19T00:00:00+00:00")   # yesterday's good board
    monkeypatch.setattr(pipeline, "refresh_due", lambda *a, **k: (True, "forced"))
    # ⚠️ A 4-TUPLE, because that is what `ingest.refresh` returns. An earlier version of this stub returned
    # a dict, and the test passed while `run()` crashed on the real type — ⭐ *a fixture that models less
    # than reality will confirm a broken mechanism.*
    monkeypatch.setattr(pipeline.ingest, "refresh", lambda *a, **k: (659, 20, 380, 20))
    monkeypatch.setattr(pipeline, "validate_board",
                        lambda *a, **k: (_ for _ in ()).throw(pipeline.BoardRejected("every player scores zero")))

    out = pipeline.run(store, now=datetime(2026, 9, 20, 18, 0, tzinfo=UTC))
    assert out["ok"] is False and "board rejected" in out["reason"]

    status = store.data_status()
    assert status["refreshed_at"].startswith("2026-09-20"), "the DATA refreshed — say so"
    assert status["ok"] == 0 and "board rejected" in status["note"], "but flag what failed, precisely"
    assert {r["computed_at"] for r in store.get_xp_board()} == {"2026-09-19T00:00:00+00:00"}, (
        "yesterday's board must still be serving")


def test_a_good_tick_reports_the_board_in_its_counts(store, monkeypatch):
    monkeypatch.setattr(pipeline, "refresh_due", lambda *a, **k: (True, "forced"))
    # ⚠️ A 4-TUPLE, because that is what `ingest.refresh` returns. An earlier version of this stub returned
    # a dict, and the test passed while `run()` crashed on the real type — ⭐ *a fixture that models less
    # than reality will confirm a broken mechanism.*
    monkeypatch.setattr(pipeline.ingest, "refresh", lambda *a, **k: (659, 20, 380, 20))
    out = pipeline.run(store, now=datetime(2026, 9, 20, 18, 0, tzinfo=UTC))
    assert out["ok"] is True
    assert out["board"]["rows"] == len(store.get_xp_board()) > 600
    assert out["counts"] == (659, 20, 380, 20), "the ingest tuple must reach describe() unchanged"


def test_the_log_line_names_the_board(store, monkeypatch):
    """⭐ *The signal that is silent is the one nobody notices has stopped.* ADR-211 learned this for
    headlines; the board gets the same treatment, including when it is deliberately skipped."""
    monkeypatch.setattr(pipeline, "refresh_due", lambda *a, **k: (True, "forced"))
    monkeypatch.setattr(pipeline.ingest, "refresh", lambda *a, **k: (659, 20, 380, 20))

    line = pipeline.describe(pipeline.run(store, now=datetime(2026, 9, 20, 18, 0, tzinfo=UTC)))
    assert "xP board" in line and "from GW6" in line, line

    monkeypatch.setattr(pipeline, "publish_board",
                        lambda *a, **k: {"rows": 0, "first_event": None, "skipped": "no upcoming fixtures"})
    line = pipeline.describe(pipeline.run(store, now=datetime(2026, 9, 20, 19, 0, tzinfo=UTC)))
    assert "xP board skipped (no upcoming fixtures)" in line, line
