"""Write the landing page's brand colour variables from `src/web_streamlit/brand.py`.

⭐⭐ **Because the alternative is a third definition of the brand.** `brand.py` is the single source of truth
(ADR-103/114) and already reaches the phone this way — `generate_brand_dart.py` writes `brand.dart` and
`tests/test_brand_dart.py` regenerates and compares, so a palette change that has not reached the app fails
the Python suite.

⚠️⚠️⚠️ **Nothing did that for `site/index.html`, and it drifted** (ADR-312): its `--ink` was **#0c0a12**
while `brand.py` said **#17131F**, and five of its colours existed nowhere central. ⭐ *The surface with a
generator did not drift; the surface without one did.* That is the whole argument.

⭐ **Only the brand block is generated.** The page's own structural values — `--bg2`, `--line`, the font
stacks — are hand-written CSS and stay that way: *a generator that owns the whole file makes every edit a
merge conflict with a script.*

Run: `venv/bin/python scripts/generate_site_palette.py`
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.web_streamlit import brand  # noqa: E402

PAGE = ROOT / "site" / "index.html"

#: CSS custom property → the `brand.py` constant behind it.
VARIABLES = {
    "purple": brand.PURPLE,
    "purple-lt": brand.PURPLE_LT,
    "green": brand.GREEN,
    "orange": brand.ORANGE,
    "yellow": brand.YELLOW,
    "ink": brand.INK,
    "bg": brand.DARK_BG,
    "panel": brand.DARK_PANEL,
    "text": brand.DARK_TEXT,
    "muted": brand.DARK_MUTED,
}

#: ⭐ The markers are a comment pair, so a reader of the CSS can see where the generated region ends without
#: consulting this file. ⚠️ *An invisible boundary is one somebody edits across.*
START = "  /* brand: generated by scripts/generate_site_palette.py — edit brand.py, then regenerate */"
END = "  /* end brand */"


def block() -> str:
    body = " ".join(f"--{name}:{value.lower()};" for name, value in VARIABLES.items())
    return f"{START}\n  {body}\n{END}"


def render(page: str) -> str:
    """The page with its brand block replaced — first run inserts it at the top of `:root{`."""
    if START in page:
        return re.sub(re.escape(START) + r".*?" + re.escape(END), block(), page, count=1, flags=re.S)
    return page.replace(":root{\n", f":root{{\n{block()}\n", 1)


def main() -> None:
    page = PAGE.read_text()
    updated = render(page)
    if updated == page:
        print("  site/index.html already current")
        return
    PAGE.write_text(updated)
    print(f"  wrote {len(VARIABLES)} brand variables into {PAGE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
