"""Generate `mobile/lib/glossary.dart` from `src/glossary.py` (ADR-249).

⭐⭐ **Generated rather than fetched.** The text is static and small, so an endpoint would spend a round
trip on something that never changes between builds — and a tooltip that has to wait for the network is a
tooltip nobody taps twice.

⚠️ Same contract as `generate_brand_dart.py`: the committed file is compared against a fresh generation by
`tests/test_glossary_dart.py`, so editing the Dart by hand fails the next run. ⭐ *A second copy of an
explanation is how the phone and the web start saying different things about the same number.*

Run: `venv/bin/python scripts/generate_glossary_dart.py`
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.glossary import TERMS  # noqa: E402

OUT = ROOT / "mobile" / "lib" / "glossary.dart"


def _dart(text: str) -> str:
    """A Dart single-quoted literal. ⚠️ Escapes the backslash first, or every other escape doubles."""
    out = text.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
    return f"'{out}'"


def render() -> str:
    entries = "\n".join(
        f"  {_dart(key)}: ({_dart(label)}, {_dart(body)}),"
        for key, (label, body) in sorted(TERMS.items())
    )
    return f"""// GENERATED by scripts/generate_glossary_dart.py — do not edit.
// ⚠️ The next line must stay EXACTLY as it is — the formatter only recognises it verbatim.
// dart format off

/// What the app's terms mean — **generated** from `src/glossary.py` (ADR-249).
///
/// ⭐⭐ One source, read by every surface. Retyping an explanation here is how the phone and the web start
/// saying different things about the same number — which is precisely what put BOOTS in white.
///
/// To change a definition: change `src/glossary.py`, then regenerate.
library;

/// term key → (short label, explanation).
const Map<String, (String, String)> glossary = {{
{entries}
}};

/// One entry, or null. ⭐ Never throws — a missing tooltip should hide, not take a screen down.
(String, String)? term(String key) => glossary[key];
"""


def main() -> None:
    OUT.write_text(render())
    print(f"  wrote {OUT.relative_to(ROOT)} ({len(TERMS)} terms, {OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
