// GENERATED by scripts/generate_glossary_dart.py — do not edit.
// ⚠️ The next line must stay EXACTLY as it is — the formatter only recognises it verbatim.
// dart format off

/// What the app's terms mean — **generated** from `src/glossary.py` (ADR-249).
///
/// ⭐⭐ One source, read by every surface. Retyping an explanation here is how the phone and the web start
/// saying different things about the same number — which is precisely what put BOOTS in white.
///
/// To change a definition: change `src/glossary.py`, then regenerate.
library;

/// term key → (short label, explanation).
const Map<String, (String, String)> glossary = {
  'bench_order': ('Bench order', 'The order FPL will substitute from if a starter plays no minutes: first, second, third, then your reserve keeper, who can only replace a keeper.'),
  'ceiling': ('Ceiling', 'The highest this week\'s confidence could reach, which is your **captain\'s own number**. Lifting it means choosing a different captain, not a different week.'),
  'confidence': ('Confidence', 'How **clear** this week\'s plan is, 1–99. It is driven by your captain and reduced by flagged players in your XI.\n\nIt is a documented heuristic, **not a probability**. Raising it does not make you more likely to be right — it means the week is less ambiguous.'),
  'defcon': ('Defensive contributions', 'Tackles, interceptions, clearances and blocks per 90 — the actions FPL now awards points for.'),
  'edge': ('Edge', 'What is going **for** you this week — a clear captain, an upgrade worth taking, points sitting on your bench.'),
  'exodus': ('Unexplained sell-off', 'Far more managers sold this player this week than his status or news explains.\n\nIt reports that **the crowd knows something we do not**. It does not say what.'),
  'free_transfers': ('Free transfers', 'How many moves you can make without a points hit. **FPL does not publish this**, so the app has to ask you for it — and the week\'s plan recommends this many moves.'),
  'grade': ('Club grade', 'A → D, from the axes that decide FPL points for a club\'s players. It is a **rank against the other nineteen**, so a D in a strong league is not the same as a D in a weak one.'),
  'lineup': ('Lineup', 'Changes to **who starts**, from the fifteen you already own. Free and reversible — no transfer is spent and nothing is bought, so this is the cheapest gain on the screen and the first one worth taking.'),
  'minutes_weight': ('Minutes weight', 'How reliably he starts, 0–1, from his recent minutes. It scales every projection: a brilliant player who plays sixty minutes is worth less than the same player playing ninety.'),
  'percentile': ('Percentile', 'A **rank**, not a score: 74 means better than 74% of the others being compared. It lets things measured in different units sit on one scale.\n\n⚠️ A high percentile in a weak field is still a high percentile.'),
  'price_direction': ('Price direction', 'Which way his price is heading, from net transfers measured against the whole board.\n\n⚠️ It does **not** say *when*. A change tonight and a change next week look the same here.'),
  'risk': ('Risk', 'What could go wrong — doubtful players, and sell-offs the data cannot explain. Each says what **kind** of claim it is, because an injury FPL confirmed and a crowd movement are not the same evidence.'),
  'timing': ('Timing', 'Whether to act **now or wait**. Prices move, news lands, and a player\'s chance of starting firms up as the deadline nears — so a move worth making is not always a move worth making yet.'),
  'transfer': ('Transfer', 'A move that **costs** something — a free transfer, or four points. The gain shown is what the move is worth over the window, so a small gain over one gameweek and the same gain over five are very different propositions.'),
  'xgi': ('xG involvement', 'Expected goals plus expected assists: the chances a player creates **and** finishes, before luck is applied.'),
  'xp': ('Expected points (xP)', 'What we project a player to score, over the window shown. It is a **projection from minutes, fixtures and underlying numbers** — not a prediction of what will happen, and not FPL\'s own figure.'),
};

/// One entry, or null. ⭐ Never throws — a missing tooltip should hide, not take a screen down.
(String, String)? term(String key) => glossary[key];
